### ISSUE TITLE
Mariano

### ISSUE THREAD

**Issue by ChrisHout** [MarianoJP/ColorSelectionComponent#1]
Hi Mariano,

Do you think it is possible to change the layout to something similar like this one?
![image](https://user-images.githubusercontent.com/80246808/126761049-f1a87f15-a933-45e5-b465-b2c4788f3fce.png)

Regards,
Chris

**Comment by ChrisHout** [comment]
Or even better, change your layout to hide the color codes and then add an 'OK' button at the bottom.
Maybe make it possible to select Layout1 (the original version) and Layout2 (version with hidden color codes)
I think adding an 'OK' button to hide the popup and select the color would be very welcome.

![image](https://user-images.githubusercontent.com/80246808/126763534-85a714e2-34ef-4d8e-b2ea-d2d52c6176f5.png)

**Comment by MarianoJP** [comment]
@ChrisHout Thank you for your comments. The ColorSelector.Razor file is very simple and acts only as a wrapper for the HTML color picker, which you are free to modify with the selections you like, however be advised that since the HTML color picker has an event that fires @onchange to triger the EventCallback<string> InvokeAsync(string) to return the color selecte to the parent. If you do not want to change the color, by simply clicking outside the pop up color picker, it will close and return to your page.

I have since looked a customization of the colorselector.razor file, such as [https://christianheilmann.com/2020/04/22/limiting-input-type-color-to-a-certain-palette-from-an-image/](url) but I leave it all to the user to select what customization they want to implement. All these changes will simply be added to the colorselector.razor file as you wish.

Remember that to use the color selector in your blazor page is as follows:

`<ColorSelector InColor="@[Your color variable you want to pass in]" ReturnedColor="[Function that will receive the string hex of the color selected]"></ColorSelector>`

Take a closer look at the Index.razor page.
